---
title: Beliefs about the effects of programming on thinking.
md_document:
  variant: gfm
  toc: yes
  toc_depth: 2
---
```{r config, include=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE,
               fig.width=4, fig.height=4, dpi=300,
               cache=TRUE)
read_chunk("beliefs.R")
```
```{r setup}
```

# Questions

```{r questions-table, results="asis"}
questions %>%
  filter(question_name %in% question_names) %>%
  select(question_name, question_text) %>%
  kable()
```

# Top 20 languages

## Changed reasoning

```{r changed-reasoning}
by_language_plot("cr1")
```

```{r functional-v-imperative}
functional_v_imperative_plot
```

## Personality

```{r personality}
by_language_plot("cp1")
```

## Recursion

```{r recursion}
by_language_plot("rec1")
```

## Code for others

```{r code-for-others}
by_language_plot("cfo1", y = 1.8)
```

## Code for team

```{r code-for-team}
by_language_plot("cfo2", y = 1.8)
```

## Interference

```{r interference}
by_language_plot("inter1", y = 4)
```

## Harm

```{r harm}
by_language_plot("inter2", y = 4)
```

# Top 8 paradigms

```{r changed-reasoning-paradigm}
by_paradigm_plot("cr1")
```

```{r personality-paradigm}
by_paradigm_plot("cp1")
```

```{r recursion-paradigm}
by_paradigm_plot("rec1")
```

```{r code-for-team-paradigm}
by_paradigm_plot("cfo2")
```

```{r interference-paradigm}
by_paradigm_plot("inter1")
```

```{r harm-paradigm}
by_paradigm_plot("inter2")
```