---
title: Programming languages
---
```{r config, include=FALSE}
library(knitr)
library(tidyverse)
library(magrittr)
opts_chunk$set(echo=FALSE, message=FALSE, fig.width=3, fig.height=3)
```

# Top languages

```{r top-languages}
source("R/sqlite.R")
source("R/question-types.R")
source("R/ranks.R")

languages <- collect_table("languages")
language_ratings <- collect_table("language_ratings")
# kable(head(languages), caption = "Sample rows of languages data.")

language_summary <- languages %>%
  group_by(language_name) %>%
  summarize(
    frequency = n(),
    proficiency = mean(proficiency, na.rm = TRUE),
    years_used = mean(years_used, na.rm = TRUE)
  ) %>%
  rank_by("frequency") %>%
  rank_by("years_used") %>%
  rank_by("proficiency")

# must be ordered!
top20_languages <- order_language_by(language_summary, "frequency_rank", levels_only = TRUE)[1:20]

not_top20_language_summary <- language_summary %>%
  filter(!(language_name %in% top20_languages)) %>%
  summarize(
    frequency = sum(frequency, na.rm = TRUE),
    years_used = mean(years_used, na.rm = TRUE),
    proficiency = mean(proficiency, na.rm = TRUE),
    frequency_rank = Inf,
    years_used_rank = Inf,
    proficiency_rank = Inf
  ) %>%
  mutate(language_name = "other")

top20_language_summary <- language_summary %>%
  filter(language_name %in% top20_languages) %>%
  bind_rows(not_top20_language_summary)

language_ratings_summary <- language_ratings %>%
  group_by(language_name, question_name, question_tag) %>%
  summarize(
    n = n(),
    agreement_num = mean(agreement_num, na.rm = TRUE)
  ) %>%
  ungroup()

top20_ratings_summary <- language_ratings_summary %>%
  filter(language_name %in% top20_languages)
```

## Frequency

```{r frequency}
top20_language_summary %<>% order_language_by("frequency_rank", reverse = TRUE)
ggplot(top20_language_summary) +
  aes(language_ordered, frequency) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x = "", y = "", title = "Frequency")
```

## Experience

```{r experience}
top20_language_summary %<>% order_language_by("years_used_rank", reverse = TRUE)
ggplot(top20_language_summary) +
  aes(language_ordered, years_used) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x = "", y = "average years used", title = "Experience")
```

## Proficiency

```{r proficiency}
top20_language_summary %<>% order_language_by("proficiency_rank", reverse = TRUE)
ggplot(top20_language_summary) +
  aes(language_ordered, proficiency) +
  geom_point(stat = "identity") +
  xlab("") +
  coord_flip(ylim = c(1, 5)) +
  labs(x = "", title = "Proficiency")
```

## Rank correlations

```{r correlations}
top20_language_summary %>%
  rank_by("proficiency") %>%
  rank_by("years_used") %>%
  filter(language_name != "other") %>%
  select(-c(frequency, proficiency, years_used, language_ordered)) %>%
  gather(rank_var, rank, -language_name) %>%
  ggplot() +
  aes(rank_var, rank, group = language_name) +
  geom_line() +
  scale_y_reverse(breaks = 1:20, labels = top20_languages) +
  theme(
    panel.grid.minor.y = element_blank()
  ) +
  labs(x = "", y = "", title = "Rank correlations")
```

```{r experience-proficiency-correlation, fig.width=8, fig.height=6}
library(ggrepel)
set.seed(543)
ggplot(filter(top20_language_summary, language_name != "other")) +
  aes(years_used, proficiency) +
  geom_point(data = filter(language_summary, !(language_name %in% top20_languages))) +
  geom_label_repel(aes(label = language_name)) +
  ggtitle("Experience-proficiency correlation")
```

## Intuitiveness

```{r intuitiveness, fig.width=6}
top20_intuitive <- filter(top20_ratings_summary, question_name == "intuitiveness")

top20_intuitive_for_all_levels <- top20_intuitive %>%
  filter(question_tag == "forAll") %>%
  rank_by("agreement_num") %>%
  order_language_by("agreement_num_rank", levels_only = TRUE)
top20_intuitive %<>% order_language_by(use_levels = top20_intuitive_for_all_levels, reverse = TRUE)

ggplot(top20_intuitive) +
  aes(language_ordered, agreement_num) +
  geom_point() +
  coord_flip(ylim = 1:5) +
  scale_y_continuous(breaks = 1:5) +
  facet_wrap("question_tag") +
  labs(x = "", y = "", title = "Intuitiveness") 
```

## Reuse

```{r reuse, fig.width=6}
recode_reuse <- function(frame) {
  reuse_levels <- c("adapt",  "reuse", "adopt")
  reuse_map <- data_frame(
    question_tag = reuse_levels,
    reuse_label = factor(reuse_levels, levels = reuse_levels)
  )
  if(missing(frame)) return(reuse_map)
  left_join(frame, reuse_map)
}

top20_reuse <- filter(top20_ratings_summary, question_name == "reuse") %>%
  recode_reuse()

top20_reuse_adaptive_levels <- top20_reuse %>%
  filter(question_tag == "adapt") %>%
  rank_by("agreement_num") %>%
  order_language_by("agreement_num_rank", levels_only = TRUE)
top20_reuse %<>% order_language_by(use_levels = top20_reuse_adaptive_levels, reverse = TRUE)

ggplot(top20_reuse) +
  aes(language_ordered, agreement_num) +
  geom_point() +
  coord_flip(ylim = 1:5) +
  scale_y_continuous(breaks = 1:5) +
  facet_wrap("reuse_label") +
  labs(x = "", y = "", title = "Reuse")
```

## Paradigms

```{r paradigms}
language_info <- collect_table("language_info")
language_info_summary <- language_info %>%
  group_by(paradigms) %>%
  summarize(n = n()) %>%
  mutate(pct = prop.table(n)) %>%
  arrange(desc(n))

top20_language_info <- language_info %>%
  filter(language_name %in% top20_languages)

top20_language_info_summary <- top20_language_info %>%
  group_by(paradigms) %>%
  summarize(n = n()) %>%
  mutate(pct = prop.table(n)) %>%
  arrange(desc(n))

top_paradigms_tbl <- left_join(top20_language_info_summary, language_info_summary, by = "paradigms", suffix = c("_top20", "_all")) %>%
  filter(row_number() <= 8)
top_paradigms <- top_paradigms_tbl$paradigms
kable(top_paradigms_tbl)

top20_language_paradigms <- top20_language_info %>%
  filter(paradigms %in% top_paradigms)

top20_language_paradigms %>%
  group_by(language_name) %>%
  summarize(n_top8_paradigms = n()) %>%
  kable()
```
